ignore:
  # Not fixed yet
  - vulnerability: CVE-2016-2781
    package:
      name: coreutils
      version: 9.3-r1
  # Not fixed yet
  - vulnerability: CVE-2020-29509
    package:
      name: go
      version: 1.20.4
  # Not fixed yet
  - vulnerability: CVE-2020-29511
    package:
      name: go
      version: 1.20.4
