#!/bin/sh

echo "NOTE: THIS SCRIPT ONLY WORKS WHEN RUNNING ON THE DEVELOPMENT IMAGE!"

DATABASE_FIXTURE_PATH="$FIXTURE_FOLDER/$EMPTY_DATABASE_FILE"

sqlite3 "$DATABASE_FIXTURE_PATH" "VACUUM;"

echo "Finished creating empty fixture sqlite file at '$DATABASE_FIXTURE_PATH'"
