name: Create Release Container

on:
  release:
    types: 
      - published

jobs:
  docker-image:
    name: Create Release Container
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: gacts/github-slug@v1
        id: slug

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin

      - name: Build the Docker image
        run: docker build -t ferdn4ndo/userver-logger-api:latest .

      - name: Tag the Docker image
        run: docker tag ferdn4ndo/userver-logger-api:latest ferdn4ndo/userver-logger-api:${{ steps.slug.outputs.version }}

      - name: Push the Docker image to the registry
        run: docker push ferdn4ndo/userver-logger-api:${{ steps.slug.outputs.version }}

      - name: Tag the GHCR Docker image
        run: docker tag ferdn4ndo/userver-logger-api:latest ghcr.io/ferdn4ndo/userver-logger-api:${{ steps.slug.outputs.version }}

      - name: Push the GHCR Docker image to the registry
        run: docker push ghcr.io/ferdn4ndo/userver-logger-api:${{ steps.slug.outputs.version }}
