name: Create Release Container

on:
  release:
    types:
      - published

jobs:
  docker-image:
    name: Create Release Container
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: gacts/github-slug@v1
        id: slug

      - name: Login to DockerHub Registry
        env:
          DOCKER_LOGIN: ${{ vars.DOCKER_LOGIN }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_LOGIN} --password-stdin

      - name: Build the Docker image
        run: >
          docker build
          --file ./Dockerfile
          --tag ferdn4ndo/userver-logger-api:latest
          --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          --build-arg BUILD_VERSION=${{ github.event.release.tag_name }}
          --build-arg VCS_REF=${GITHUB_SHA}
          .

      - name: Tag the versioned Docker image
        run: docker tag ferdn4ndo/userver-logger-api:latest ferdn4ndo/userver-logger-api:${{ steps.slug.outputs.version }}

      - name: Push the versioned Docker image to the registry
        run: docker push ferdn4ndo/userver-logger-api:${{ steps.slug.outputs.version }}

      - name: Push the latest Docker image to the registry
        run: docker push ferdn4ndo/userver-logger-api:latest

      - name: Login to GitHub Container Repository (GHCR)
        run: echo ${{ secrets.GHCR_PASSWORD }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag the versioned GHCR Docker image
        run: docker tag ferdn4ndo/userver-logger-api:latest ghcr.io/ferdn4ndo/userver-logger-api:${{ steps.slug.outputs.version }}

      - name: Push the versioned GHCR Docker image to the registry
        run: docker push ghcr.io/ferdn4ndo/userver-logger-api:${{ steps.slug.outputs.version }}
