name: Label Issues And Pull Requests

on:
  issues:
    types:
      - opened
      - edited
      - closed
      - reopened
  pull_request:
    types: 
      - opened
      - edited
      - closed
      - reopened
      - ready_for_review
      - synchronize

permissions:
  contents: read

jobs:
  label-issues-and-pull-requests:
    name: Label Issues And Pull Requests
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Set up Checkout
        uses: actions/checkout@v2

      - name: Run IvanFon/super-labeler-action
        uses: IvanFon/super-labeler-action@v1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
