name: Codebase Quality

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**.md'
    tags-ignore:
      - '**'
  pull_request:
    paths-ignore:
      - '**.md'

jobs: # Docs: <https://git.io/JvxXE>
  check-codebase-quality:
    name: Check codebase quality with ReviewDog
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Setup golangci-lint
        uses: reviewdog/action-golangci-lint@v2

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1

      - name: Run linter (gofumpt -s) with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go install mvdan.cc/gofumpt@v0.2.0
          gofumpt -e -d . | \
          reviewdog -name="gofumpt" -f=diff -f.diff.strip=0 -reporter=github-pr-review
